# Discord Configuration
discord:
  token: bot_token_here
  command_prefix: "!"
  allowed_channels:
    - general  # Optional: restrict bot to specific channels

# Scripts Configuration
scripts:
  data_collection:
    path: "collect_data.py"
    # Add any specific parameters your collection script needs
  analysis:
    path: "analyze_options.py"
    # Add any default parameters your analysis script needs

# State Configuration
state:
  file_path: "bot_state.json"
