# Discord Configuration
discord:
  token: removed
  command_prefix: "!"
  allowed_channels:
    - removed  # Optional: restrict bot to specific channels

# Scripts Configuration
scripts:
  base_path: "path to /SchwabV2"
  virtual_env: "path to /SchwabV2/.venv/Scripts/python.exe"
  data_collection:
    command: "collect-data"  # Using the entry point from setup.py
  analysis:
    command: "analyze-options"  # Using the entry point from setup.py
    default_args: []  # Any default arguments you want to always include

# State Configuration
state:
  file_path: "bot_state.json"

